apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: redisapp
  name: redisapp
spec:
  replicas: 1 # 3
  selector:
    matchLabels:
      app: redisapp
  strategy: {}
  template:
    metadata:
      labels:
        app: redisapp
    spec:
      containers:
        - image: kota661/session-redis:latest
          name: session-redis
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 250m
              memory: 512Mi

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: redisapp
  name: redisapp
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
      nodePort: 30002
  selector:
    app: redisapp
  type: NodePort
status:
  loadBalancer: {}
---

